version: '2'
services:
    app:
        container_name: "app-insights"
        image: node:8
        volumes:
            - .:/usr/app/
        ports:
            - 3000:3000
        links:
            - mongodb
        depends_on:
            - mongodb
        command: "npm run dev"

    mongodb:
        image: mongo:latest
        container_name: "db-insights"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
          - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet